version: '3.8'

services:
  rranjan-java-app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "8001:8001"
    environment:
      - ELASTIC_APM_SERVICE_NAME=rranjan-java-app
      - ELASTIC_APM_SERVER_URL=<Add url APM URL Here>
      - ELASTIC_APM_SECRET_TOKEN=<ADD your APM secret Code Here>
      - ELASTIC_APM_ENVIRONMENT=demo
    networks:
      - javaapplication_app-network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8080:8080"
    networks:
      - javaapplication_app-network

networks:
  javaapplication_app-network:
    driver: bridge
